/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class Blob {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Blob(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Blob obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_Blob(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Blob() {
    this(irohaJNI.new_Blob__SWIG_0(), true);
  }

  public Blob(String blob) {
    this(irohaJNI.new_Blob__SWIG_1(blob), true);
  }

  public Blob(ByteVector blob) {
    this(irohaJNI.new_Blob__SWIG_2(ByteVector.getCPtr(blob), blob), true);
  }

  public static Blob fromHexString(String hex) {
    return new Blob(irohaJNI.Blob_fromHexString(hex), true);
  }

  public ByteVector blob() {
    return new ByteVector(irohaJNI.Blob_blob(swigCPtr, this), false);
  }

  public String hex() {
    return irohaJNI.Blob_hex(swigCPtr, this);
  }

  public long size() {
    return irohaJNI.Blob_size(swigCPtr, this);
  }

  public String toString() {
    return irohaJNI.Blob_toString(swigCPtr, this);
  }

  public boolean b_equal(Blob rhs) {
    return irohaJNI.Blob_b_equal(swigCPtr, this, Blob.getCPtr(rhs), rhs);
  }

}
