/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class iroha {
  public static String toBinaryString(Blob b) {
    return irohaJNI.toBinaryString(Blob.getCPtr(b), b);
  }

}
