/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class ModelTransactionBuilder {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModelTransactionBuilder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModelTransactionBuilder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_ModelTransactionBuilder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ModelTransactionBuilder() {
    this(irohaJNI.new_ModelTransactionBuilder(), true);
  }

  public ModelTransactionBuilder creatorAccountId(String account_id) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_creatorAccountId(swigCPtr, this, account_id), true);
  }

  public ModelTransactionBuilder createdTime(java.math.BigInteger created_time) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_createdTime(swigCPtr, this, created_time), true);
  }

  public ModelTransactionBuilder addAssetQuantity(String account_id, String asset_id, String amount) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_addAssetQuantity(swigCPtr, this, account_id, asset_id, amount), true);
  }

  public ModelTransactionBuilder addPeer(String address, PublicKey peer_key) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_addPeer(swigCPtr, this, address, PublicKey.getCPtr(peer_key), peer_key), true);
  }

  public ModelTransactionBuilder addSignatory(String account_id, PublicKey public_key) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_addSignatory(swigCPtr, this, account_id, PublicKey.getCPtr(public_key), public_key), true);
  }

  public ModelTransactionBuilder removeSignatory(String account_id, PublicKey public_key) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_removeSignatory(swigCPtr, this, account_id, PublicKey.getCPtr(public_key), public_key), true);
  }

  public ModelTransactionBuilder appendRole(String account_id, String role_name) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_appendRole(swigCPtr, this, account_id, role_name), true);
  }

  public ModelTransactionBuilder createAsset(String asset_name, String domain_id, short precision) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_createAsset(swigCPtr, this, asset_name, domain_id, precision), true);
  }

  public ModelTransactionBuilder createAccount(String account_name, String domain_id, PublicKey main_pubkey) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_createAccount(swigCPtr, this, account_name, domain_id, PublicKey.getCPtr(main_pubkey), main_pubkey), true);
  }

  public ModelTransactionBuilder createDomain(String domain_id, String default_role) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_createDomain(swigCPtr, this, domain_id, default_role), true);
  }

  public ModelTransactionBuilder createRole(String role_name, StringVector permissions) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_createRole(swigCPtr, this, role_name, StringVector.getCPtr(permissions), permissions), true);
  }

  public ModelTransactionBuilder detachRole(String account_id, String role_name) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_detachRole(swigCPtr, this, account_id, role_name), true);
  }

  public ModelTransactionBuilder grantPermission(String account_id, String permission) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_grantPermission(swigCPtr, this, account_id, permission), true);
  }

  public ModelTransactionBuilder revokePermission(String account_id, String permission) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_revokePermission(swigCPtr, this, account_id, permission), true);
  }

  public ModelTransactionBuilder setAccountDetail(String account_id, String key, String value) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_setAccountDetail(swigCPtr, this, account_id, key, value), true);
  }

  public ModelTransactionBuilder setAccountQuorum(String account_id, long quorum) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_setAccountQuorum(swigCPtr, this, account_id, quorum), true);
  }

  public ModelTransactionBuilder subtractAssetQuantity(String account_id, String asset_id, String amount) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_subtractAssetQuantity(swigCPtr, this, account_id, asset_id, amount), true);
  }

  public ModelTransactionBuilder transferAsset(String src_account_id, String dest_account_id, String asset_id, String description, String amount) {
    return new ModelTransactionBuilder(irohaJNI.ModelTransactionBuilder_transferAsset(swigCPtr, this, src_account_id, dest_account_id, asset_id, description, amount), true);
  }

  public UnsignedTx build() {
    return new UnsignedTx(irohaJNI.ModelTransactionBuilder_build(swigCPtr, this), true);
  }

}
