/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class Signed extends Blob {
  private transient long swigCPtr;

  protected Signed(long cPtr, boolean cMemoryOwn) {
    super(irohaJNI.Signed_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Signed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_Signed(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Signed(String blob) {
    this(irohaJNI.new_Signed__SWIG_0(blob), true);
  }

  public Signed(ByteVector blob) {
    this(irohaJNI.new_Signed__SWIG_1(ByteVector.getCPtr(blob), blob), true);
  }

  public String toString() {
    return irohaJNI.Signed_toString(swigCPtr, this);
  }

}
