/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class SWIGTYPE_p_boost__any_rangeT_shared_model__interface__Signature_const_R_boost__forward_traversal_tag_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_boost__any_rangeT_shared_model__interface__Signature_const_R_boost__forward_traversal_tag_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_boost__any_rangeT_shared_model__interface__Signature_const_R_boost__forward_traversal_tag_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_boost__any_rangeT_shared_model__interface__Signature_const_R_boost__forward_traversal_tag_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

