/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class UnsignedTx {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnsignedTx(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedTx obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_UnsignedTx(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedTx(Transaction o) {
    this(irohaJNI.new_UnsignedTx__SWIG_0(Transaction.getCPtr(o), o), true);
  }

  public Transaction signAndAddSignature(Keypair keypair) {
    return new Transaction(irohaJNI.UnsignedTx_signAndAddSignature(swigCPtr, this, Keypair.getCPtr(keypair), keypair), true);
  }

  public Hash hash() {
    return new Hash(irohaJNI.UnsignedTx_hash(swigCPtr, this), true);
  }

}
