/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jp.co.soramitsu.iroha.android;

public class UnsignedQuery {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UnsignedQuery(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UnsignedQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        irohaJNI.delete_UnsignedQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UnsignedQuery(Query o) {
    this(irohaJNI.new_UnsignedQuery__SWIG_0(Query.getCPtr(o), o), true);
  }

  public Query signAndAddSignature(Keypair keypair) {
    return new Query(irohaJNI.UnsignedQuery_signAndAddSignature(swigCPtr, this, Keypair.getCPtr(keypair), keypair), true);
  }

  public Hash hash() {
    return new Hash(irohaJNI.UnsignedQuery_hash(swigCPtr, this), true);
  }

}
